### ISSUE TITLE
Document setup for devcontainer

### ISSUE THREAD

**Issue by amirbtb** [innoverio/vscode-dbt-power-user#117]
Hello,

I have a simple dbt project inside a devcontainer (VSCode in a remote container) based on an ubuntu image.
On the opening of devcontainer, the **vscode-dbt-power-user** launches a terminal to run `dbt list` and it runs successfully and prints all the nodes. But no functionality is added to  
Details to reproduce the error : 
- I am using Python 3.8.10 with dbt 1.1.1
- The `dbt debug` command shows no issues
- The dbt project path is `/src`
- This is the content of the `.devcontainer/devcontainer.json` : 
```
{
  "name": "dbt devcontainer",
  "dockerComposeFile": "../docker-compose.yml",
  "service": "dbt",
  "workspaceFolder": "/src",
  "shutdownAction": "stopCompose",
  "extensions": [
    "innoverio.vscode-dbt-power-user"
  ],
  "settings": {
    "files.associations": {
      "*.sql": "jinja-sql"
    }
  }
}
```

I saw other issues related to this (for instance [dbt shows connected but extension has zero functionality](https://github.com/innoverio/vscode-dbt-power-user/issues/111)) but it didn't show me a missing setting in my setup.
Did I forget something ? Thank you for your help !

**Comment by dataders** [comment]
I'm also trying to get this to run in a codespace and am getting a related issue upon booting
> Cannot activate the 'dbt Power User' extension because it depends on the 'Python' extension, which is not installed. Would you like to install the extension and reload the window?

When I look what extensions are installed, it says the Python extension _is_ installed already...
![image](https://user-images.githubusercontent.com/8158673/181049404-dd50a21d-67fb-475f-ad5e-3ae7c8efecf5.png)

**Comment by korompaiistvan** [comment]
@dataders I fixed this same issue by leaving out the python extension from my list of extensions in devcontainer.json (since the dbt power user extension is going to install the python one anyways).
this is an issue with many other extensions, where VSCode doesn't "merge" dependencies. nothing the authors of this one can do about it unfortunately

**Comment by amirbtb** [comment]
Hello @dataders thank you for your help !
I just tried to remove `ms-python.python` from my `.devcontainer/devcontainer.json` but I still have the same issues with the extension.

**Comment by alexeyegorov** [comment]
@korompaiistvan Thanks! That worked for me. I was following this instructions here: https://github.com/davidgasquez/dbt-devcontainer 
I then removed both Python dependencies and now it works like a charm!

**Comment by dataders** [comment]
y'all should check out this demo repo in a codespace. lots of the nice-to-haves in one place
https://github.com/dbt-labs/jaffle_shop_duckdb

**Comment by mdesmet** [comment]
If someone figures out how to set it up, please make a PR and provide instructions in the README.

**Comment by mdesmet** [comment]
There are lots of people having succesfully setup this.

See for example: https://github.com/davidgasquez/dbt-devcontainer
