### ISSUE TITLE
Old macro version is used in preview

### ISSUE THREAD

**Issue by RobbertDM** [innoverio/vscode-dbt-power-user#346]
### Expected behavior

When a macro is updated and the file is saved, when executing the macro in a model preview, the newest version should run.

### Actual behavior

When a macro is updated and the file is saved, when executing the macro in a model preview, an old version is run.

### Steps To Reproduce

I haven't tried this, but I expect this should work:
* Write a macro that selects 1 (`test_macro.sql`):
```jinja
{% macro test_macro() %}
  select 1
{% endmacro %}
```
* Call the macro from a model (`test_macro_model.sql`):
```
{{ test_macro() }}
```
* Preview the output of the model. Verify that the output is `1`
* Modify the macro to select 2. Save the file.
* Preview the output of the model again. Verify that the output is still `1`, as opposed to the expected `2`.

### Operating System

Ubuntu 22.04

### dbt version

1.4.1

### dbt Adapter

trino

### dbt Power User version

v0.11.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by RobbertDM** [comment]
restarting vscode does yield the desired result

**Comment by mdesmet** [comment]
Interesting, I'll have a look. I would expect any change in sql files to result in a partial parse of the project.

**Comment by hdao3363** [comment]
I have the same issue also. Is there anyway that I can refresh/update the macro in the preview without restarting vscode? Much appreciate

**Comment by mdesmet** [comment]
Fixed in 0.12.1

**Comment by RobbertDM** [comment]
I'm still having this issue, sort of. I'm on `v.0.13.0`.

When I modify the macro, save, and run the preview, it uses the old version.
When saving the macro, indeed, `manifest.json` and `partial_parse.mspack` get updated. All the rest in the target folder stays the same. The partial parse file indeed already contains the new macro.

When I run `dbt test` (which uses the macro) however, some more files get updated (`graph.gpickle` and the sql files in `compiled/` and `run/`), but nothing that I believe matters here, unless you're relying on the timestamp of any of those files to check whether a new macro is available?

After running `dbt test`, when I run the preview, it's using the new macro.

**Comment by RobbertDM** [comment]
Yes a bunch of things are different but nothing that really matters I think.
I've found now that it's just this `manifest.json` that takes a few (~5) seconds to write back.

![Screencast from 17-05-23 23:26:38.webm](https://github.com/innoverio/vscode-dbt-power-user/assets/117672004/c814aac2-051e-4827-adcf-68c61573a88b)

The msgpack file isn't any faster.
