### ISSUE TITLE
dbt power user not detecting dbt

### ISSUE THREAD

**Issue by sdepablos** [innoverio/vscode-dbt-power-user#76]
System:
- Manjaro 21.1.0
- Python 3.9.6
- VSCode 1.57.0 with just two extensions, Python and dbt power user plus dependencies (to try to isolate the issue)
- Virtualenv in the project directory, with dbt 0.20.0 installed (and working)

Every time I try to open the dbt power user extension, I get the error message "Please ensure DBT is installed in your selected Python environment"

As you can see in the screenshot, the selected Python environment is Python 3.9.6 on a virtual environment, and right next to it you see how the dbt extension is detected (check mark), but I get the message anyways.

![Screenshot from 2021-07-19 08-17-09](https://user-images.githubusercontent.com/211364/126112312-4c5e10a4-6abb-4ce5-8b00-b4538dce367f.png)

On the extension, no models appear by default (as it's not detecting dbt), but if I load an SQL file on the IDE, I get it to appear on the extension, although pressing play just gives me the same error

![image](https://user-images.githubusercontent.com/211364/126113048-5e8cd4d0-b903-471c-9daf-f340d029c594.png)

Below the dbt log. It properly detects there're two models (right now I'm using a base dbt project after a `dbt init`)
```
2021-07-19 06:14:11.684583 (MainThread): Running with dbt=0.20.0
2021-07-19 06:14:12.215687 (MainThread): running dbt with arguments Namespace(record_timing_info=None, debug=False, log_format='default', write_json=True, use_colors=None, strict=False, warn_error=False, partial_parse=None, single_threaded=True, test_new_parser=False, use_experimental_parser=False, project_dir=None, profiles_dir='/home/sergi/.dbt', profile=None, target=None, vars='{}', log_cache_events=False, use_cache=True, resource_types=[], output='selector', models=None, select=None, exclude=None, selector_name=None, state=None, defer=None, cls=<class 'dbt.task.list.ListTask'>, which='list', rpc_method=None)
2021-07-19 06:14:12.217058 (MainThread): Tracking: do not track
2021-07-19 06:14:12.240458 (MainThread): Partial parsing not enabled
2021-07-19 06:14:12.251595 (MainThread): Parsing macros/adapters.sql
2021-07-19 06:14:12.297446 (MainThread): Parsing macros/catalog.sql
2021-07-19 06:14:12.305151 (MainThread): Parsing macros/etc.sql
2021-07-19 06:14:12.308203 (MainThread): Parsing macros/materializations/snapshot.sql
2021-07-19 06:14:12.312021 (MainThread): Parsing macros/materializations/table.sql
2021-07-19 06:14:12.326956 (MainThread): Parsing macros/materializations/seed.sql
2021-07-19 06:14:12.330794 (MainThread): Parsing macros/materializations/view.sql
2021-07-19 06:14:12.334695 (MainThread): Parsing macros/materializations/incremental.sql
2021-07-19 06:14:12.353065 (MainThread): Parsing macros/materializations/copy.sql
2021-07-19 06:14:12.362029 (MainThread): Parsing macros/core.sql
2021-07-19 06:14:12.368017 (MainThread): Parsing macros/materializations/test.sql
2021-07-19 06:14:12.378441 (MainThread): Parsing macros/materializations/helpers.sql
2021-07-19 06:14:12.392252 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-07-19 06:14:12.425338 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-07-19 06:14:12.495199 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-07-19 06:14:12.498658 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-07-19 06:14:12.542635 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-07-19 06:14:12.549507 (MainThread): Parsing macros/materializations/view/view.sql
2021-07-19 06:14:12.557406 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-07-19 06:14:12.568944 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-07-19 06:14:12.572244 (MainThread): Parsing macros/materializations/common/merge.sql
2021-07-19 06:14:12.592826 (MainThread): Parsing macros/materializations/table/table.sql
2021-07-19 06:14:12.602024 (MainThread): Parsing macros/adapters/common.sql
2021-07-19 06:14:12.670824 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-07-19 06:14:12.672386 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-07-19 06:14:12.675534 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-07-19 06:14:12.677825 (MainThread): Parsing macros/schema_tests/unique.sql
2021-07-19 06:14:12.679584 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-07-19 06:14:12.680758 (MainThread): Parsing macros/etc/datetime.sql
2021-07-19 06:14:12.693341 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-07-19 06:14:12.696036 (MainThread): Parsing macros/etc/is_incremental.sql
2021-07-19 06:14:12.698236 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-07-19 06:14:12.700539 (MainThread): Parsing macros/etc/query.sql
2021-07-19 06:14:13.023916 (MainThread): Acquiring new bigquery connection "model.base.my_second_dbt_model".
2021-07-19 06:14:13.041182 (MainThread): Acquiring new bigquery connection "model.base.my_first_dbt_model".
2021-07-19 06:14:13.084479 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-07-19 06:14:13.087679 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-07-19 06:14:13.092453 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-07-19 06:14:13.095499 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-07-19 06:14:13.124272 (MainThread): Found 2 models, 4 tests, 0 snapshots, 0 analyses, 164 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-07-19 06:14:13.125533 (MainThread): Flushing usage events
2021-07-19 06:14:13.125771 (MainThread): Connection 'model.base.my_first_dbt_model' was properly closed.
```

**Comment by sdepablos** [comment]
I've been investigating a little (without being a JS expert) an AFAIK this happens with version 0.20.0. but not but 0.19.2. Following the code I see that in `dbt_client/index.ts` in `checkIfDBTIsIntalled`

```js
  async checkIfDBTIsInstalled(): Promise<void> {
    const checkDBTInstalledProcess = this.executeCommand(
      this.dbtCommandFactory.createImportDBTCommand()
    );

    this.raiseDBTInstallationCheckEvent();
    try {
      await checkDBTInstalledProcess.complete();
    }catch(_) {
      this.raiseDBTNotInstalledEvent();
      return;
    }

    const checkDBTVersionProcess = this.executeCommand(
      this.dbtCommandFactory.createVersionCommand()
    );
    const timeoutCmd = new Promise((resolve, _) => {
      setTimeout(resolve, 5000, 'Could not connect');
    });
    try {
      await Promise.race([
        checkDBTVersionProcess.complete(),
        timeoutCmd,
      ]);
      checkDBTVersionProcess.dispose();
    } catch (err) {
      if (err.match(DBTClient.IS_INSTALLED)) {
        this.checkIfDBTIsUpToDate(err);
        return;
      }
    }
    this.raiseDBTVersionCouldNotBeDeterminedEvent();
  }
```

The `catch(err) is only triggered when the dbt version is < 0.20, so when it's 0.20 the `checkIfDBTIsUpToDate` is never triggered and the `installed` it's never set to true (it stays on undefined). No idea why

**Comment by mdesmet** [comment]
Thanks Sergi! I will have a look later today.

**Comment by sdepablos** [comment]
Thanks @mdesmet, but don't spend time on this, I've just upgraded to VSCode 1.58.2 and everything is working back again. I went to the upgrade way because even the Better Jinja was unable to open the files, it was looking for them in the /app directory that does not even exists on my project (it looks like there was some cache issue somewhere, because that's the path inside one docker image I've been using)

**Comment by sdepablos** [comment]
Hi @mdesmet, today VSCode was not working again, so I kept investigating, and I've finally found the issue. Basically this 
```js
    const timeoutCmd = new Promise((resolve, _) => {
      setTimeout(resolve, 5000, 'Could not connect');
    });
```
was giving a timeout. In my machine, `dbt --version`  has a longer execution time with 0.20.0 (~6 seconds) than with 0.19.2 (~4 seconds), but sometimes it does it under 5 seconds, and that's when it was working.

Apart from giving a longer startup time - maybe even configurable on the extension - I think something like this would be advisable (again, not a JS expert)

```javascript
    try {
      const result = await Promise.race([
        checkDBTVersionProcess.complete(),
        timeoutCmd,
      ]);
      window.showErrorMessage("Timeout connecting to DBT");
      checkDBTVersionProcess.dispose();
    } catch (err) {
      if (err.match(DBTClient.IS_INSTALLED)) {
        this.checkIfDBTIsUpToDate(err);
        return;
      }
    }
```
 Whatever the solution, at least for me it looks like 5 seconds is not always enough

**Comment by mdesmet** [comment]
Got it, actually it should just detect dbt if under 5 seconds, just the version won't be detected. I will investigate later today and provide a fix.

**Comment by sdepablos** [comment]
Thanks @mdesmet . 

For now I've increased the timeout, and the extension is working for me, but after listing the models, they don't appear on the menu (they appear in the terminal but not on the extension). 

![image](https://user-images.githubusercontent.com/211364/126331107-b50ebe0b-4c63-491c-b951-c3bfbf958107.png)

**Comment by mdesmet** [comment]
Fixed in 0.5.5! Let me know if it works for you.

**Comment by sdepablos** [comment]
@mdesmet yes, it works. I still don't get the version (sometimes it takes more than 6 seconds to detect the version) but at least it does not stop executing DBT. Thanks a lot! I close the issue.
